name: lm-bio-kgc
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- cudatoolkit=10.1
- ipdb
- ipython
- matplotlib
- numpy
- pandas
- pip
- scipy
- seaborn
- scikit-learn
- pytorch==1.6.0
- tqdm
- transformers==3.3.1
- pip:
    - accelerate
    - beautifulsoup4
    - biopython
    - networkx
    - nltk
    - ogb
    - tensorboardX
    - xgboost
